TODO list for Linear Algebra http://joshua.smcvt.edu/linearalgebra 


* Look through bug reports

** subsectionoptional results in pdf errors in the log file about math shift,
leaves extra space at start of first sentence.



* New material

** SAGE? Lab manual?

** Cover art?
   
** Hestenes?

** Include handwritten versions of lower case Greek letters on flyleaf?

** Add Topic on error correcting codes?

** Add Topic on graphs are isomorphic iff their adjacency matrices are similar?

** Change orientation of spine text 
** Topic on Principle Components
** Better Topic on graphics
** Get source for four_minute_mile.pdf, moneyball.pdf
** For proof that every basis si the same size, put the coordinate-bound one on the slides
* Refactor some code 
** Move Range space and Null space to after the definition of Computing Linear Maps
** Change vector look?
  http://www.reddit.com/r/LaTeX/comments/m4lxo/both_of_these_arrows_look_wrong_to_me_pic/

** XeLaTeX?

would allow a wide variety of fonts.  Does it limit graphics file input types,
etc?  See http://www.tug.org/pipermail/xetex/2011-August/021006.html

** Switch from MetaPost to Asymptote?

Like MetaPost but also 3D, and some sane control structures and data types?

*** including cleaning up loose files; find a place to put the .aux's 

Graphics files can have their own directory

other files need to be in the same dir as each other because of the need for
one file to read from another?  That is, cannot put files by chapter?

See http://tex.stackexchange.com/questions/37167/sorting-logs-into-different-folders

** Use the numprint package?
  http://www.ctan.org/pkg/numprint

** Adjust ch2.mp figure numbers to be in sensibel order, starting with 1.

** Get latexmk to compile without the empty .asy files (if there were .pdf's with numbers like xxx00.pdf and xxx01.pdf then as a hack I put in a couple of xxx00.asy-type files.)
* Give it a less-flat format
In particular, the metapost outputs cluttering the dir are a mess.
** Have an INSTALL file
** Have a Contributing file
* Try .cls

** Maybe various formats, different color schemes?

** Perhaps depending on command line choice?
  pdflatex euler book



* e-book format?
  Tried breqn but changing the equation* environment on line 1938 of gr1.tex
  to dmath* did not result in a break.  Puzzled.

** Convert to ebook, using the newly-available options through tex4ht
** See if can document them whil I do it.
